sudo: required
dist: trusty

language: node_js
node_js:
  - "8.7.0"

# services:
  # - docker

cache: 
  paths:
    - ./server/node_modules/
    - ./server/client/node_modules/

before_script:
  - npm --prefix ./server install
  - npm --prefix ./server/client install

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm --prefix ./server/client run test
  - npm --prefix ./server/client run e2e
  - npm --prefix ./server/client run build --prod --base-href /