sudo: required
dist: trusty

language: node_js
node_js:
  - "8.7.0"

services:
  - docker

cache: 
  paths:
    - node_modules/

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta

before_script:
  - npm install -g @angular/cli
  - npm install -g karma
  - npm --prefix ./client install
  - npm --prefix ./server install

script:
  - npm --prefix ./client run test
  - npm --prefix ./client run e2e
  - npm --prefix ./client run build --prod --base-href /