sudo: required
dist: trusty
language: node_js
node_js:
- 8.7.0
cache:
  paths:
  - "./node_modules"
  - "./client/node_modules"
before_script:
- npm install
- npm --prefix ./client install
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm --prefix ./client run test
- npm --prefix ./client run e2e
- npm --prefix ./client run build --prod --base-href /
deploy:
  provider: heroku
  api_key:
    secure: RwZ7biGO015CcX4PAvIYoVCptTWlIAusj0yappis1y6yDCTO1dhYRGexsM8TMte38oMZQY5aYepT9rCQJeC3+ycLFikvB94ckOJSwH8MmxrO3uJxa+kwaqxGhEVD056vlRXSS8ZZzUbA9ajjCDqalhG0glRNh9Oa4FF26+24x41jKNpI8qy14OagoD1zKWSEkuaG9n9bdFAxGJ9QX0SU+QPieBkpVgH9GYoSxz8+dKEvxrSDngkKbUSvvUQBcQO43qvfNaiFSW8s7/qS7qCsSA35LgQ0ML97sSsrAjzG0wb6l/wl5wTgXbt3/mV87u+PhpSPFM6AI6rYS4LDdxsJK6UcMc7vQ6503XyGZ1M1SOp9gS2EJQdVjUKp3PzK3vA6b+6pqQA7KA7Y9Byd57RpNq3KncDRAjPh+WK0CDb7S8ypyKv4J9GFnplISQDB5UEuL5TVtAu8ubKE2HHu7YyXsJ4c8QwnvS4aqLsCtwws4FcK9XCIM1sh894R2t+Qqd87j2EOKO7eETh66GM9lAZcWKHNXnwiuqluSsZwCLRdG+lgODmhhHZMxegB05p1ECHV9DihEcvCSQgo/VNSBZHns3Tg7NwCZR59enk5gU/sY9TGXLnqsbwvtfkIj3gdlJX9QnpFgljscwap2twE45wECvGBiCnSKl2ZwDjhBCwvEHg=
  app: worobye
  run: "npm deploy"
