version: '3.3'
services:
  # web:
  #   build: .
  #   depends_on:
  #     - db
  #   ports:
  #     - "3000:3000"
  db:
    image: "postgres"
    ports:
      - "5432:5432"
  dbadmin:
    image: "chorss/docker-pgadmin4"
    ports:
      - "5050:5050"
