version: '3.3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  client:
    build:
      context: ./server/client
      dockerfile: Dockerfile
    ports: 
      - "80:4200"
    command: "npm run test"
  db:
    image: postgres:latest
    ports:
      - "5432:5432"